# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

ruby '3.0.2'

gem 'rails', '~> 6.1.4', '>= 6.1.4.1'

gem 'dry-initializer'
gem 'dry-validation'
gem 'dry-monads'

gem 'dotenv-rails'

gem 'pg', '~> 1.1'

gem 'puma', '~> 5.0'

gem 'bootsnap', '>= 1.4.4', require: false

gem 'devise'
gem 'devise-jwt'

gem 'rack-cors'

group :development, :test do
  gem 'pry'
  gem 'rails-pry'
  gem 'rubocop'
  gem 'rubocop-rails'
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
